name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Prepare docs
        run: .buildscript/prepare_mkdocs.sh

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Restore Javadocs from 1.x
        run: git cherry-pick b3205fa199a19d6fbf13ee5c8e0c3d6d2b15b05f

      - name: Push gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GH_TOKEN }}
